// Package compiler implements the goatc build pipeline.
package compiler

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/torrischen/goat/goatc/config"
	"gopkg.in/yaml.v3"
)

// Result describes a completed build.
type Result struct {
	Output string
}

// Build compiles all configured plugins and the generated agent executable.
func Build(configPath, outputOverride string, log io.Writer) (*Result, error) {
	if log == nil {
		log = io.Discard
	}
	absoluteConfig, err := filepath.Abs(configPath)
	if err != nil {
		return nil, fmt.Errorf("resolve config path: %w", err)
	}
	cfg, err := config.Load(absoluteConfig)
	if err != nil {
		return nil, err
	}

	projectDir := filepath.Dir(absoluteConfig)
	moduleRoot, err := findModuleRoot(projectDir)
	if err != nil {
		return nil, err
	}
	buildDir, err := os.MkdirTemp(moduleRoot, ".goatc-build-")
	if err != nil {
		return nil, fmt.Errorf("create build directory: %w", err)
	}
	defer os.RemoveAll(buildDir)

	pluginsDir := filepath.Join(buildDir, "plugins")
	if err := os.MkdirAll(pluginsDir, 0o755); err != nil {
		return nil, fmt.Errorf("create plugin directory: %w", err)
	}

	for _, tool := range cfg.Tools {
		source := tool.Source
		if !filepath.IsAbs(source) {
			source = filepath.Join(projectDir, source)
		}
		source, err = filepath.Abs(source)
		if err != nil {
			return nil, fmt.Errorf("resolve source for %s: %w", tool.Name, err)
		}
		output := filepath.Join(pluginsDir, tool.Name+".so")
		fmt.Fprintf(log, "building plugin %s\n", tool.Name)
		if err := buildPlugin(source, output, cfg.Build.Tags, log); err != nil {
			return nil, fmt.Errorf("build plugin %s: %w", tool.Name, err)
		}
	}

	normalizedConfig, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("encode normalized config: %w", err)
	}
	if err := os.WriteFile(filepath.Join(buildDir, "goatc.yaml"), normalizedConfig, 0o644); err != nil {
		return nil, fmt.Errorf("write embedded config: %w", err)
	}
	if err := os.WriteFile(filepath.Join(buildDir, "main.go"), []byte(generatedMain), 0o644); err != nil {
		return nil, fmt.Errorf("write generated main: %w", err)
	}

	output := outputOverride
	if output == "" {
		output = cfg.Build.Output
	}
	if !filepath.IsAbs(output) {
		output = filepath.Join(projectDir, output)
	}
	output, err = filepath.Abs(output)
	if err != nil {
		return nil, fmt.Errorf("resolve output path: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return nil, fmt.Errorf("create output directory: %w", err)
	}

	relativeBuildDir, err := filepath.Rel(moduleRoot, buildDir)
	if err != nil {
		return nil, fmt.Errorf("resolve generated package: %w", err)
	}
	args := []string{"build", "-trimpath", "-o", output}
	if len(cfg.Build.Tags) > 0 {
		args = append(args, "-tags", strings.Join(cfg.Build.Tags, ","))
	}
	args = append(args, "./"+filepath.ToSlash(relativeBuildDir))
	fmt.Fprintln(log, "building agent binary")
	if err := runGo(moduleRoot, args, log); err != nil {
		return nil, fmt.Errorf("build agent binary: %w", err)
	}

	return &Result{Output: output}, nil
}

func buildPlugin(source, output string, tags []string, log io.Writer) error {
	info, err := os.Stat(source)
	if err != nil {
		return err
	}
	args := []string{"build", "-trimpath", "-buildmode=plugin", "-o", output}
	if len(tags) > 0 {
		args = append(args, "-tags", strings.Join(tags, ","))
	}

	workingDir := source
	if info.IsDir() {
		args = append(args, ".")
	} else {
		if filepath.Ext(source) != ".go" {
			return fmt.Errorf("source must be a directory or .go file: %s", source)
		}
		workingDir = filepath.Dir(source)
		args = append(args, filepath.Base(source))
	}
	return runGo(workingDir, args, log)
}

func runGo(dir string, args []string, output io.Writer) error {
	command := exec.Command("go", args...)
	command.Dir = dir
	command.Stdout = output
	command.Stderr = output
	command.Env = os.Environ()
	if err := command.Run(); err != nil {
		return fmt.Errorf("go %s: %w", strings.Join(args, " "), err)
	}
	return nil
}

func findModuleRoot(start string) (string, error) {
	dir := start
	for {
		if info, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found above %s", start)
		}
		dir = parent
	}
}

const generatedMain = `// Code generated by goatc. DO NOT EDIT.
package main

import (
	"context"
	"embed"
	"log"

	goatcruntime "github.com/torrischen/goat/goatc/runtime"
)

//go:embed goatc.yaml plugins/*.so
var assets embed.FS

func main() {
	if err := goatcruntime.Run(context.Background(), assets); err != nil {
		log.Fatal(err)
	}
}
`
